version: '2'

services: 
  haproxy:
    container_name: haproxy
    build: haproxy/.
    ports:
        - "80:80"
        - "70:70"
    expose:
        - "80"
        - "70"
    links:
        - mysql_db

  mysql_db:
    container_name: mysql_db
    build: mysql_db/.
    ports:
        - "3306"
        - "3380:80"
    expose:
        - "3306"
        - "3380"

# Not yet Supported
#networks:
#    default:
#        driver: custom-driver-1
